Revision
ermshaua/preon pull request #3
Opened 2023-09-12 07:07 UTC by ermshaua

This pull request contains the changes made for the paper revision. Specifically, I implemented

1. store functions for reference EBI / DrugBank data, to make preon more easy to use
2. rounding to edit distance (as a parameter)
3. informative user warnings if no match is found (as a parameter)

Tests and examples were checked and adapted accordingly.

2023-09-12 09:47 UTC, mbenary requested changes
Please follow up on the documentation. Otherwise, it looks good.

2023-09-12 09:47 UTC, mbenary commented on preon/drug.py
> +    :param file_path: the file that should be stored.
More precise, maybe like: 

> Path to the local file which should be included in the preon instance.

2023-09-12 09:47 UTC, mbenary commented on preon/drug.py
> +
Why are you selecting columns from the ebi-file? That should be part of the help-description.

2023-09-12 09:47 UTC, mbenary commented on preon/drug.py
> +    columns = ["Name", "Synonyms", "ChEMBL ID"]
Consider refactoring. The same column names are used in load_ebi_drugs. If there is a change later on, we have to fix it twice.

2023-09-12 09:47 UTC, mbenary commented on preon/drug.py
> +def store_drugbank_drugs(file_path):
Feature request for later: Create a general `store_xxx` function, which has parameters for file-path and column-names.

2023-09-13 08:09 UTC, ermshaua commented on preon/drug.py
> +    :param file_path: the file that should be stored.
Done.

2023-09-13 08:11 UTC, ermshaua commented on preon/drug.py
> +
I'm checking if the local file contains the required columns for loading and parsing. If I don't do this, we potentially store files we cannot load, which is an inconsistent state we do not want to have. Added the help description.

2023-09-13 08:11 UTC, ermshaua commented on preon/drug.py
> +    columns = ["Name", "Synonyms", "ChEMBL ID"]
Done.

2023-09-13 08:14 UTC, ermshaua commented on preon/drug.py
> +def store_drugbank_drugs(file_path):
Yeah, maybe. Currently, we only store files we can load (specific store and load functions). If we add this, we store files that we cannot load. This should be discussed some time. Note, however, that the user can load any file she wants and fit preon with it, independent of the file being a local resource or not!

2023-09-13 08:16 UTC, ermshaua commented
@mbenary Thanks for your feedback. I added it and discussed some points (see above). I would merge the changes now, if that's fine with you.

2023-11-28 14:37 UTC, merged